--data:extend({
--   {
--        type = "string-setting",
--        name = "my-custom-input",
--        setting_type = "runtime-global",
--        default_value = "yes",
--        allowed_values = {"yes", "no"}
--    },
--   {
--        type = "bool-setting",
--        name = "my-mod-kill-player-on-entity-built",
--       setting_type = "runtime-per-user",
--       default_value = false
--    }
--})